use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};

const ASSETS: &[&str] = &[
    "LICENSE",
    "common/keyword_checklist.txt",
    "common/morpheme_checklist.txt",
    "ml_model/ml_config.json",
    "ml_model/ml_model.onnx",
    "rules/config.yaml",
    "secret/config.json",
];

#[derive(Deserialize)]
struct Rule {
    name: String,
    severity: Option<String>,
    confidence: Option<String>,
    #[serde(rename = "type")]
    kind: Option<String>,
    values: Option<Vec<String>>,
    min_line_len: Option<usize>,
    required_substrings: Option<Vec<String>>,
    filter_type: Option<OneOrMany>,
    use_ml: Option<bool>,
    target: Option<Vec<String>>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum OneOrMany {
    One(String),
    Many(Vec<String>),
}

#[derive(Deserialize)]
struct SourceManifest {
    assets: BTreeMap<String, String>,
}

fn main() {
    verify_assets();
    let source = Path::new("vendors/credsweeper-assets/rules/config.yaml");
    println!("cargo:rerun-if-changed={}", source.display());
    let yaml = fs::read_to_string(source).expect("read embedded CredSweeper rules");
    let rules: Vec<Rule> = serde_yaml::from_str(&yaml).expect("parse embedded CredSweeper rules");
    validate_patterns(&rules);
    let generated = generate(&rules, yaml.len());
    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("credsweeper_rules.rs");
    fs::write(output, generated).expect("write generated CredSweeper rules");
}

fn validate_patterns(rules: &[Rule]) {
    for rule in rules {
        if rule.kind.as_deref() != Some("pattern") || rule.name == "BASE64 Private Key" {
            continue;
        }
        for pattern in rule.values.as_deref().unwrap_or_default() {
            if regex::Regex::new(pattern).is_err() && fancy_regex::Regex::new(pattern).is_err() {
                panic!(
                    "embedded CredSweeper regex for rule {:?} is unsupported; update the generated assets",
                    rule.name
                );
            }
        }
    }
}

fn verify_assets() {
    let root = Path::new("vendors/credsweeper-assets");
    let manifest_path = root.join("SOURCE.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let manifest: SourceManifest = serde_json::from_slice(
        &fs::read(&manifest_path).expect("read CredSweeper source manifest"),
    )
    .expect("parse CredSweeper source manifest");
    let expected = ASSETS
        .iter()
        .copied()
        .collect::<std::collections::BTreeSet<_>>();
    let actual = manifest
        .assets
        .keys()
        .map(String::as_str)
        .collect::<std::collections::BTreeSet<_>>();
    assert_eq!(actual, expected, "CredSweeper manifest asset list changed");
    for relative in ASSETS {
        let path = root.join(relative);
        println!("cargo:rerun-if-changed={}", path.display());
        let expected_hash = &manifest.assets[*relative];
        let actual_hash = file_sha256(&path);
        assert_eq!(
            actual_hash, *expected_hash,
            "CredSweeper asset hash mismatch: {relative}; run tools/update_credsweeper.py"
        );
    }
}

fn file_sha256(path: &Path) -> String {
    let file = fs::File::open(path).expect("open CredSweeper asset");
    let mut reader = BufReader::new(file);
    let mut digest = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = reader.read(&mut buffer).expect("hash CredSweeper asset");
        if read == 0 {
            break;
        }
        digest.update(&buffer[..read]);
    }
    digest
        .finalize()
        .iter()
        .fold(String::with_capacity(64), |mut output, byte| {
            write!(output, "{byte:02x}").expect("write SHA-256");
            output
        })
}

fn generate(rules: &[Rule], yaml_bytes: usize) -> String {
    let mut out = format!(
        "// @generated by crates/pentect-core/build.rs; do not edit.\n\
         const GENERATED_RULES_YAML_BYTES: usize = {yaml_bytes};\n\
         fn generated_raw_rules() -> Vec<RawRule> {{\n    vec![\n"
    );
    for rule in rules {
        let filters = match &rule.filter_type {
            None => "None".to_string(),
            Some(OneOrMany::One(value)) => {
                format!("Some(FilterList::One({}.to_string()))", literal(value))
            }
            Some(OneOrMany::Many(values)) => {
                format!("Some(FilterList::Many({}))", string_vec(values))
            }
        };
        writeln!(
            out,
            "        RawRule {{ name: {}.to_string(), severity: {}, confidence: {}, kind: {}, values: {}, min_line_len: {}, required_substrings: {}, filter_type: {filters}, use_ml: {}, target: {} }},",
            literal(&rule.name),
            optional_string(&rule.severity),
            optional_string(&rule.confidence),
            optional_string(&rule.kind),
            optional_vec(&rule.values),
            optional_usize(rule.min_line_len),
            optional_vec(&rule.required_substrings),
            optional_bool(rule.use_ml),
            optional_vec(&rule.target),
        )
        .expect("write generated rule");
    }
    out.push_str("    ]\n}\n");
    out
}

fn literal(value: &str) -> String {
    format!("{value:?}")
}

fn optional_string(value: &Option<String>) -> String {
    value
        .as_deref()
        .map(|value| format!("Some({}.to_string())", literal(value)))
        .unwrap_or_else(|| "None".to_string())
}

fn optional_vec(value: &Option<Vec<String>>) -> String {
    value
        .as_ref()
        .map(|values| format!("Some({})", string_vec(values)))
        .unwrap_or_else(|| "None".to_string())
}

fn string_vec(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| format!("{}.to_string()", literal(value)))
        .collect::<Vec<_>>()
        .join(", ");
    format!("vec![{values}]")
}

fn optional_usize(value: Option<usize>) -> String {
    value.map_or_else(|| "None".to_string(), |value| format!("Some({value})"))
}

fn optional_bool(value: Option<bool>) -> String {
    value.map_or_else(|| "None".to_string(), |value| format!("Some({value})"))
}
